version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_inspection
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7
    container_name: smart-redis
    ports:
      - "6379:6379"
    networks:
      - smart-net

  backend:
    image: ghcr.io/love796-qaq/smartinspection-backend:main
    container_name: smart-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_inspection?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - smart-net

  frontend:
    image: ghcr.io/love796-qaq/smartinspection-frontend:main
    container_name: smart-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smart-net

networks:
  smart-net:
    driver: bridge

volumes:
  mysql_data:
